FROM node

# RUN npm init -y

# # RUN npm install react

# # RUN npm install react-dom

# RUN node --version

# RUN npm --version

# RUN npx WORKETYAMO


# FROM ubuntu:22.04

RUN apt update

RUN  apt install npm

RUN npm --version

RUN node --version

RUN npm -g install create-react-app

RUN create-react-app --version

RUN create-react-app WORKETYAMO

RUN cd WORKETYAMO

RUN npm start